async function ExtractIdModule(moduleArg={}){var Module=moduleArg;var n=import.meta.url,p="",q;try{p=(new URL(".",n)).href}catch{}q=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var t=console.log.bind(console),u=console.error.bind(console),v=!1;function x(){if(!y?.buffer?.l){a:{try{var a=z.toResizableBuffer();break a}catch{}a=z.buffer}y=new Int8Array(a);new Int16Array(a);Module.HEAPU8=A=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);B=new Uint32Array(a);new Float32Array(a);new Float64Array(a);
new BigInt64Array(a);new BigUint64Array(a)}}function C(){var a=Module.preRun;a&&(typeof a=="function"&&(a=[a]),D.push(...a));for(a=D;a.length>0;)a.shift()(Module)}function E(){var a=Module.postRun;a&&(typeof a=="function"&&(a=[a]),F.push(...a));for(a=F;a.length>0;)a.shift()(Module)}function G(a){Module.onAbort?.(a);a=`Aborted(${a})`;u(a);v=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var H;async function I(a){try{var b=await q(a);return new Uint8Array(b)}catch{}throw"both async and sync fetching of the wasm failed";
}async function J(a,b){try{var d=await I(a);return await WebAssembly.instantiate(d,b)}catch(c){u(`failed to asynchronously prepare wasm: ${c}`),G(c)}}async function K(a){var b=H;try{var d=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(d,a)}catch(c){u(`wasm streaming compile failed: ${c}`),u("falling back to ArrayBuffer instantiation")}return J(b,a)}var y,B,A,F=[],D=[],L=globalThis.TextDecoder&&new TextDecoder,M=(a,b=0,d,c)=>{var e=b;d=e+d;if(c)c=d;else{for(;a[e]&&
!(e>=d);)++e;c=e}if(c-b>16&&a.buffer&&L)return L.decode(a.subarray(b,c));for(e="";b<c;)if(d=a[b++],d&128){var g=a[b++]&63;if((d&224)==192)e+=String.fromCharCode((d&31)<<6|g);else{var f=a[b++]&63;d=(d&240)==224?(d&15)<<12|g<<6|f:(d&7)<<18|g<<12|f<<6|a[b++]&63;d<65536?e+=String.fromCharCode(d):(d-=65536,e+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else e+=String.fromCharCode(d);return e},N=[null,[],[]],O=(a,b,d)=>{var c=A;if(!(d>0))return 0;var e=b;d=b+d-1;for(var g=0;g<a.length;++g){var f=a.codePointAt(g);
if(f<=127){if(b>=d)break;c[b++]=f}else if(f<=2047){if(b+1>=d)break;c[b++]=192|f>>6;c[b++]=128|f&63}else if(f<=65535){if(b+2>=d)break;c[b++]=224|f>>12;c[b++]=128|f>>6&63;c[b++]=128|f&63}else{if(b+3>=d)break;c[b++]=240|f>>18;c[b++]=128|f>>12&63;c[b++]=128|f>>6&63;c[b++]=128|f&63;g++}}c[b]=0;return b-e},S=(a,b,d,c)=>{var e={string:h=>{var k=0;if(h!==null&&h!==void 0&&h!==0){for(var l=k=0;l<h.length;++l){var w=h.charCodeAt(l);w<=127?k++:w<=2047?k+=2:w>=55296&&w<=57343?(k+=4,++l):k+=3}k+=1;l=P(k);O(h,
l,k);k=l}return k},array:h=>{var k=P(h.length);y.set(h,k);return k}};a=Module["_"+a];var g=[],f=0;if(c)for(var m=0;m<c.length;m++){var r=e[d[m]];r?(f===0&&(f=Q()),g[m]=r(c[m])):g[m]=c[m]}d=a(...g);return d=function(h){f!==0&&R(f);return b==="string"?h?M(A,h):"":b==="boolean"?!!h:h}(d)};Module.print&&(t=Module.print);Module.printErr&&(u=Module.printErr);var T=Module.preInit;if(T)for(typeof T=="function"&&(Module.preInit=T=[T]);T.length>0;)T.shift()();Module.ccall=S;Module.cwrap=(a,b,d,c)=>{var e=!d||
d.every(g=>g==="number"||g==="boolean");return b!=="string"&&e&&!c?Module["_"+a]:(...g)=>S(a,b,d,g,c)};Module.UTF8ToString=(a,b,d)=>a?M(A,a,b,d):"";Module.stringToUTF8=(a,b,d)=>O(a,b,d);var R,P,Q,z,U={a:(a,b,d,c)=>G(`Assertion failed: ${a?M(A,a):""}, at: `+[b?b?M(A,b):"":"unknown filename",d,c?c?M(A,c):"":"unknown function"]),c:a=>{var b=A.length;a>>>=0;if(a>2147483648)return!1;for(var d=1;d<=4;d*=2){var c=b*(1+.2/d);c=Math.min(c,a+100663296);a:{c=(Math.min(2147483648,Math.ceil(Math.max(a,c)/65536)*
65536)-z.buffer.byteLength+65535)/65536|0;try{z.grow(c);x();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},b:(a,b,d,c)=>{for(var e=0,g=0;g<d;g++){var f=B[b>>2],m=B[b+4>>2];b+=8;for(var r=0;r<m;r++){var h=a,k=A[f+r],l=N[h];k===0||k===10?((h===1?t:u)(M(l)),l.length=0):l.push(k)}e+=m}B[c>>2]=e;return 0}},V;V=await (async function(){function a(c){c=V=c.exports;Module._malloc=c.f;Module._free=c.g;Module._extract_id=c.h;R=c.i;P=c.j;Q=c.k;z=c.d;x();return V}var b={a:U},d=Module.instantiateWasm;
if(d)return new Promise(c=>{d(b,e=>c(a(e)))});H??=Module.locateFile?Module.locateFile?Module.locateFile("extract_id.wasm",p):p+"extract_id.wasm":(new URL("extract_id.wasm",import.meta.url)).href;return function(c){return a(c.instance)}(await K(b))}());await (async function(){C();var a=Module.setStatus;a&&(a("Running..."),await new Promise(b=>setTimeout(b,1)),setTimeout(a,1,""));v||(V.e(),Module.onRuntimeInitialized?.(),E())}());;return Module}export default ExtractIdModule;
