import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './admin.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#121414',
        'surface-dim': '#121414',
        'surface-bright': '#37393a',
        'surface-container-lowest': '#0c0f0f',
        'surface-container-low': '#1a1c1c',
        'surface-container': '#1e2020',
        'surface-container-high': '#282a2b',
        'surface-container-highest': '#333535',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#c1c6d8',
        'inverse-surface': '#e2e2e2',
        'inverse-on-surface': '#2f3131',
        outline: '#8c90a1',
        'outline-variant': '#414655',
        'surface-tint': '#afc6ff',
        primary: '#afc6ff',
        'on-primary': '#002d6d',
        'primary-container': '#548dff',
        'on-primary-container': '#002760',
        'inverse-primary': '#0058c9',
        secondary: '#ddfcff',
        'on-secondary': '#00363a',
        'secondary-container': '#00f1fe',
        'on-secondary-container': '#006a70',
        tertiary: '#ffb598',
        'on-tertiary': '#591d00',
        'tertiary-container': '#f1651e',
        'on-tertiary-container': '#4e1800',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        favorite: '#4ade80',
        'on-favorite': '#042713',
        'primary-fixed': '#d9e2ff',
        'primary-fixed-dim': '#afc6ff',
        'on-primary-fixed': '#001944',
        'on-primary-fixed-variant': '#00429a',
        'secondary-fixed': '#74f5ff',
        'secondary-fixed-dim': '#00dbe7',
        'on-secondary-fixed': '#002022',
        'on-secondary-fixed-variant': '#004f54',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb598',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7e2c00',
        background: '#121414',
        'on-background': '#e2e2e2',
        'surface-variant': '#333535',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        gutter: '24px',
        'container-max': '960px',
      },
      fontFamily: {
        'display-lg': ['Inter'],
        'headline-xl': ['Inter'],
        'headline-xl-mobile': ['Inter'],
        'headline-lg': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-caps': ['Inter'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '800' }],
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['14.5px', { lineHeight: '1.65', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
